# Generated by Django 3.0 on 2021-06-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tienda',
        ),
    ]
